library(readr)
library(dplyr) 
library(ggplot2)
redData <- read_csv("StudyArea.csv", col_types = list(UNIT = col_character(), OUTDATED = col_character()), col_names = TRUE)
selData = select(redData, STATE, YR = YEAR_, ORGANIZATI, ACRES = TOTALACRES, CAUSE)
selData = filter(selData, ACRES >= 1000)
mutData <- mutate(selData, DECADE = ifelse(YR %in% 1980:189, "1980-1989", ifelse(YR %in% 1990:1999, "1990-1999", ifelse(YR %in% 2000:2009, "2000-2009", ifelse(YR %in% 2010:2016, "2010-2016", "-99")))))
grpData <- group_by(mutData, DECADE)
sumData <- summarize(grpData, mean(ACRES))
names(sumData) <- c("DECADE", "MEAN_ACRES_BURNED")
ggplot(data = sumData) + geom_col(mapping = aes(x = DECADE, y = MEAN_ACRES_BURNED), fill = "red")
